db:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://qrowd-project.eu/"
  volumes:
    - ./data/virtuoso:/data
  ports:
    - "8890:8890"
