PREFIX  dbo:  <http://dbpedia.org/ontology/>
PREFIX  lgdo: <http://linkedgeodata.org/ontology/>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?s ?sl ?t ?tl
WHERE
  { SERVICE <http://dbpedia.org/sparql>
      { ?s  <http://www.w3.org/2000/01/rdf-schema#label>  ?sl ;
            rdf:type              dbo:Airport
      }
    SERVICE <http://linkedgeodata.org/sparql>
      { ?t  <http://www.w3.org/2000/01/rdf-schema#label>  ?tl ;
            rdf:type              lgdo:Airport
      }
    { SELECT  ?s
      # FROM <http://qrowd-project.eu/>
      WHERE
        { ?s  owl:sameAs  ?t }
    }
  }
